[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
svag = { path = ".." }
minijinja = "2"
reqwest = { version = "0.12", features = ["blocking"] }
flate2 = "1"
tar = "0.4"
rapidhash = "1"
ignore = "0.4"
serde_json = "1"
